"""DUDU-BLDC source validation."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from trustworthy_agent.data.manifest import CANONICAL_CLASSES, CANONICAL_CSV_FILES
from trustworthy_agent.data.schema import DatasetSchema, discover_schema, write_schema_reports


@dataclass(frozen=True)
class ValidationReport:
    """Structured validation report for input or analysis data.

    Purpose:
        Represent pass/fail status, machine-readable reasons, and evidence.
    Parameters:
        valid: Overall validation status.
        reason_codes: Machine-readable validation reason codes.
        details: Structured validation evidence.
    Return value:
        Immutable validation report.
    Raised exceptions:
        None.
    Scientific assumptions:
        Validation checks source structure only; no model or result claims.
    Side effects:
        None.
    Reproducibility implications:
        Stable reason codes support scripted failure handling.
    """

    valid: bool
    reason_codes: tuple[str, ...]
    details: dict[str, Any]

    def to_json_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable validation report."""

        return {
            "valid": self.valid,
            "reason_codes": list(self.reason_codes),
            "details": self.details,
        }


def validate_dudu_bldc(project_root: Path) -> ValidationReport:
    """Discover and validate DUDU-BLDC source schema.

    Purpose:
        Implement the canonical data validation CLI workflow.
    Parameters:
        project_root: Repository root.
    Return value:
        ValidationReport with explicit reason codes.
    Raised exceptions:
        FileNotFoundError if no DUDU-BLDC source root exists.
    Scientific assumptions:
        Canonical class labels come from `SPEC.md`; grouping identifiers are
        reported only when actually discovered.
    Side effects:
        Writes schema and validation reports under `Output/`.
    Reproducibility implications:
        Validation can be rerun from immutable local source files.
    """

    source_root = source_data_root(project_root)
    schema = discover_schema(source_root)
    report = validate_schema(schema)
    output_root = project_root / "Output"
    write_schema_reports(schema, output_root)
    manifest_root = output_root / "Manifests"
    manifest_root.mkdir(parents=True, exist_ok=True)
    (manifest_root / "dataset_validation.json").write_text(
        json.dumps(report.to_json_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return report


def describe_dudu_bldc(project_root: Path) -> tuple[DatasetSchema, ValidationReport]:
    """Return discovered schema and validation without changing source data.

    Purpose:
        Implement the canonical data description CLI workflow.
    Parameters:
        project_root: Repository root.
    Return value:
        Tuple of schema and validation report.
    Raised exceptions:
        FileNotFoundError if no source root exists.
    Scientific assumptions:
        None beyond canonical labels for validation.
    Side effects:
        Writes the same deterministic schema-audit reports as validation.
    Reproducibility implications:
        Ensures descriptions are generated by code from local source files.
    """

    report = validate_dudu_bldc(project_root)
    schema = discover_schema(source_data_root(project_root))
    return schema, report


def source_data_root(project_root: Path) -> Path:
    """Locate the immutable DUDU-BLDC source tree.

    Purpose:
        Prefer extracted data when present while preserving the raw archive.
    Parameters:
        project_root: Repository root.
    Return value:
        Path to extracted or raw DUDU-BLDC root.
    Raised exceptions:
        FileNotFoundError when the source tree is unavailable.
    Scientific assumptions:
        None.
    Side effects:
        None.
    Reproducibility implications:
        Keeps source lookup project-relative.
    """

    base = project_root / "Data/InputData/External/DUDU-BLDC-v1"
    extracted = base / "extracted"
    if extracted.exists():
        return extracted
    if base.exists():
        return base
    raise FileNotFoundError(f"DUDU-BLDC source root not found: {base}")


def validate_schema(schema: DatasetSchema) -> ValidationReport:
    """Validate discovered schema against DUDU-BLDC source requirements.

    Purpose:
        Convert schema facts into explicit pass/fail reason codes.
    Parameters:
        schema: Discovered schema.
    Return value:
        ValidationReport.
    Raised exceptions:
        None.
    Scientific assumptions:
        The canonical classes are fixed; feature columns are not hardcoded.
    Side effects:
        None.
    Reproducibility implications:
        Reason codes make schema failures script-detectable.
    """

    reason_codes: list[str] = []
    details: dict[str, Any] = {
        "files_discovered": len(schema.files),
        "expected_files_present": list(schema.expected_files_present),
        "expected_files_missing": list(schema.expected_files_missing),
        "unexpected_csv_files": list(schema.unexpected_csv_files),
        "available_identifiers": sorted(
            {
                identifier
                for file_schema in schema.files
                for identifier in file_schema.available_identifiers
            }
        ),
    }
    if not schema.files:
        reason_codes.append("NO_CSV_FILES")
    if schema.expected_files_missing:
        reason_codes.append("MISSING_EXPECTED_ANALYTICAL_FILES")
    for file_schema in schema.files:
        if file_schema.duplicated_columns:
            reason_codes.append("DUPLICATED_COLUMNS")
        if not file_schema.columns:
            reason_codes.append("NO_COLUMNS")
        unexpected_labels = [
            label for label in file_schema.class_labels if label not in CANONICAL_CLASSES
        ]
        if unexpected_labels:
            reason_codes.append("UNEXPECTED_CLASS_LABELS")
        if Path(file_schema.path).name in CANONICAL_CSV_FILES and not file_schema.class_labels:
            reason_codes.append("NO_CLASS_EVIDENCE")
    return ValidationReport(
        valid=not reason_codes,
        reason_codes=tuple(sorted(set(reason_codes))),
        details=details,
    )
