"""Audit event schema constants."""

AUDIT_EVENT_FIELDS: tuple[str, ...] = (
    "schema_version",
    "event_type",
    "event_id",
    "event_index",
    "run_id",
    "experiment_fingerprint",
    "case_id",
    "window_id",
    "timestamp",
    "state_from",
    "state_to",
    "transition_policy",
    "transition_policy_version",
    "candidate_states",
    "raw_transition_scores",
    "normalized_probabilities",
    "selected_state",
    "selection_mode",
    "rng_seed_or_stream_id",
    "active_state_strategy",
    "strategy_version",
    "strategy_params_hash",
    "safety_rules_evaluated",
    "safety_rules_triggered",
    "safety_override",
    "diagnosis",
    "class_probabilities",
    "confidence",
    "spline_summary",
    "explanation_score",
    "top_explanatory_features",
    "risk_score",
    "ood_score",
    "decision_reason",
    "final_action",
    "input_hash",
    "config_hash",
    "model_hash",
    "git_commit",
    "previous_event_hash",
    "event_hash",
)

AUDIT_SCHEMA_VERSION = "1.0"
